Load feed
droidconKE/flutterconKEApp pull request #54
Opened 2024-08-08 16:26 UTC by DevshiDeno

## Description
load feed issue

I created the necessary models required to handle event feeds gotten from the API and used Cubit to track state on the feed UI screen.
## Type of Change
enhancement

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [x] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Test Changes on Device
You can download your APK from Firebase App Distribution once this PR builds successfully via the following link: https://appdistribution.firebase.dev/i/c796669942f8a811

2024-08-08 18:53 UTC, MillerAdulu commented
@DevshiDeno 

Kindly add a video description to showcase the interaction of the UI concerning this feature.

2024-08-08 19:00 UTC, DevshiDeno commented
Okay

On Thu, Aug 8, 2024, 9:53 PM Miller Adulu ***@***.***> wrote:

> @DevshiDeno <https://github.com/DevshiDeno>
>
> Kindly add a video description to showcase the interaction of the UI
> concerning this feature.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/droidconKE/flutterconKEApp/pull/54#issuecomment-2276459060>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYQBRLZQXSMTN6GJKI764PDZQO5CNAVCNFSM6AAAAABMG2XQE2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENZWGQ2TSMBWGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-08 19:01 UTC, MillerAdulu requested changes

2024-08-08 19:01 UTC, MillerAdulu commented on lib/features/feed/cubit/feed_cubit.dart
> +      final feeds = await _apiRepository.fetchFeeds(event: '');
The slug for the feed of this event as per the documentation at this URL should be `droidconke-2022-281`

https://documenter.getpostman.com/view/3385291/SzS4TTXb#a443ec01-1cf8-41d9-bfd5-56fb6c228de4

Please make this slight addition.

2024-08-08 19:01 UTC, MillerAdulu commented on linux/flutter/ephemeral/.plugin_symlinks/path_provider_linux
Delete this file.

2024-08-08 19:01 UTC, MillerAdulu commented on linux/flutter/generated_plugin_registrant.cc
Delete this file.

2024-08-08 19:01 UTC, MillerAdulu commented on linux/flutter/generated_plugin_registrant.h
Delete this file.

2024-08-08 19:01 UTC, MillerAdulu commented on linux/flutter/generated_plugins.cmake
Delete this file.

2024-08-08 19:01 UTC, MillerAdulu commented on macos/Flutter/GeneratedPluginRegistrant.swift
Delete this file.

2024-08-08 19:01 UTC, MillerAdulu commented on macos/Flutter/ephemeral/Flutter-Generated.xcconfig
Delete this file.

2024-08-08 19:01 UTC, MillerAdulu commented on macos/Flutter/ephemeral/flutter_export_environment.sh
Delete this file.

2024-08-08 19:02 UTC, MillerAdulu commented
@DevshiDeno,

Once you are done with the changes, check the failing pipeline here: https://github.com/droidconKE/flutterconKEApp/actions/runs/10305939605/job/28533957201?pr=54

Fix the formatting issue by running the `fmt` command in the `Makefile`

2024-08-08 19:03 UTC, MillerAdulu commented
The code generally looks OK. Looking forward to the corrections and this can be merged in quickly.

2024-08-11 11:04 UTC, MillerAdulu commented
@DevshiDeno,

Trusting that you are still on this.

2024-08-11 11:38 UTC, DevshiDeno commented
Yes, I am working on it.

On Sun, Aug 11, 2024, 2:05 PM Miller Adulu ***@***.***> wrote:

> @DevshiDeno <https://github.com/DevshiDeno>,
>
> Trusting that you are still on this.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/droidconKE/flutterconKEApp/pull/54#issuecomment-2282719822>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYQBRL6JVOCLE37VNPXRVDTZQ5AO5AVCNFSM6AAAAABMG2XQE2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBSG4YTSOBSGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-14 09:21 UTC, MillerAdulu commented
@rebase

2024-08-14 09:22 UTC, MillerAdulu commented
Made changes on #59 that's now merged. Closing

2024-08-14 09:22 UTC, closed without merging